CUDA_VISIBLE_DEVICES=1 python main.py \
    --computer_id 1 \
    --reward_assign 1.0 \
    --multi_cnn 0 \
    --use_k_max_pool 1 \
    --num_k 1 \
    --add_linear 0 \
    --epochs 10 \
    --positive_rate 0.75 \
    --load_weights '' \
    --save_weights_prefix '' \
    --gpu_rate 0.10 \
    --result_dir 'results/fw99_multicnn0_nk1_rw2_linear0_base'
